services:
  EXSyst\NormalizerExtraBundle\Listener\JsonRequestListener:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 128 }
