services:
  EXSyst\NormalizerExtraBundle\Listener\RequestDecoderListener:
    arguments:
      $context: '%exsyst_normalizer_extra.default_context%'
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 128 }
