services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EXSyst\NormalizerExtraBundle\Listener\JsonRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 128 }
