services:
  EXSyst\NormalizerExtraBundle\Compiler\SpecializedNormalizerCompiler:
    autowire: true
    autoconfigure: true
    public: false

  EXSyst\NormalizerExtraBundle\Normalizer\SpecializingNormalizer:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - { name: serializer.normalizer, priority: -999 }
