services:
  EXSyst\NormalizerExtraBundle\Compiler\SpecializedNormalizerCompiler:
    arguments:
      $cacheDirectory: '%kernel.cache_dir%/exsyst-normalizer-extra/specialized-normalizers'
    autowire: true
    autoconfigure: true
    public: false

  EXSyst\NormalizerExtraBundle\Normalizer\SpecializingNormalizer:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - { name: serializer.normalizer, priority: -999 }
