services:
  EXSyst\NormalizerExtraBundle\Listener\SerializerExceptionListener:
    arguments:
      $context: '%exsyst_normalizer_extra.default_context%'
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -96 }
