services:
  EXSyst\NormalizerExtraBundle\Normalizer\CollectionNormalizer:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - { name: serializer.normalizer, priority: -989 }
