services:
  EXSyst\NormalizerExtraBundle\Metadata\AutoNormalizableMetadataProvider:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - { name: exsyst.normalizer_extra.property_provider, priority: 255 }
