services:
  EXSyst\NormalizerExtraBundle\Metadata\ChainNormalizableMetadataProvider:
    arguments:
      $providers: null
    autowire: true
    autoconfigure: false
    public: false
    lazy: true

  EXSyst\NormalizerExtraBundle\Metadata\NormalizableMetadataProviderInterface:
    alias: EXSyst\NormalizerExtraBundle\Metadata\ChainNormalizableMetadataProvider

  EXSyst\NormalizerExtraBundle\Normalizer\BreadthFirstNormalizer:
    arguments:
      $implicit: '%exsyst_normalizer_extra.implicit_breadth_first%'
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - { name: serializer.normalizer, priority: 32767 }
